### PR TITLE
Add a "safe mode" setting (on by default)

### PR DESCRIPTION
**Pull request by cpitclaudel**
In safe mode, prompt and offer a tip on how to disable safe mode before
running "continue".

Connected to #82.

### CODE REVIEW

**Comment by rocky** [comment]
Wow! Many thanks! (Want to commit directly to this repo?)

**Comment by cpitclaudel** [comment]
Direct commit access would be convenient, but I'd still go through pull requests :) The benefit would be that I could merge them myself when you give the green light, and I wouldn't need to bother you for small things like typos.

Also, fair warning: I don't know how much time I'll end up spending working on this. RealGUD is extremely good, but I don't know how often I'll find occasions to contribute :)

**Comment by rocky** [comment]
> Also, fair warning: I don't know how much time I'll end up spending working on this. RealGUD is extremely good, but I don't know how often I'll find occasions to contribute :)

That makes two of us.

**Comment by cpitclaudel** [comment]
> Except I think it RealGUD needs lots more work

I'm sure I'll agree once the wow-factor wears off :) Meanwhile, this is the only package that I know off that comes close to replicating the experience that I had years ago when I worked with Visual Studio.

Since most of the code has FSF headers already, have you considered hosting this package on ELPA? It could give it a visibility boost, and it should be pretty easy copyright-wise: I already have FSF copyright papers on file, and most other external contributions yours seem small, except those @seanfarley. Sean, have you signed FSF copyright papers in the past?

I'm thinking that hosting this on ELPA could be a first step towards giving this package broader visibility. We might even hope for more external contributions (and even in the long run merging this into Emacs itself?!)

**Comment by rocky** [comment]
It is approved for inclusion into ELPA, papers were signed a while ago. I just haven't put it there. 

Maybe after you do a clean up I will.

**Comment by cpitclaudel** [comment]
Neat! Ok, I'll keep this in mind :)

**Comment by rocky** [comment]
Actually, it is there in a branch right now: http://git.savannah.gnu.org/cgit/emacs/elpa.git?h=realgud

**Pull request merged**
