### PR TITLE
Add ipdb debugger with tab completion

### LINKED ISSUE #70: tab completion
I was hoping to write ipdb support for realgud but it seems that the comint buffer handling the debugger doesn't handle tab completion. Is this a deep emacs issue or could it be made to work with debuggers that have tab completion? (or perhaps I'm doing something wrong?)

### PR DESCRIPTION
**Pull request by seanfarley**
This should fix #70. It adds the ipdb debugger and tab completion. Currently, it uses `comint`-based methods but feedback is welcomed for more generic methods.

### CODE REVIEW

**Comment by rocky** [comment]
Looked at this some more. How about some tests for the code which you can cull from  `test/test-pdb.el`, `test/test-regexp-pdb.el`,  and `test/test-bt-pdb.el`? 

Also I don't see any specific code for tab completion beyond what may be there for _pdb_. Is there any?

**Comment by seanfarley** [comment]
It's `realgud:ipdb-backend-complete` but I had to rebase and fix an error in it (which I'll push up in a minute). Also, yes, totally agree about adding tests.

If I understand correctly, if I want to add this to melpa I'll need to split this into another repo. Is that right?

**Comment by rocky** [comment]
> If I understand correctly, if I want to add this to melpa I'll need to split this into another repo. Is that right?

It can get onto melpa via this repo. But it isn't automatic as normal commits because folks on the Melpa side have to do something special right now. Since there already are a fair number python debuggers, some that I've written and consider obsolete, if we go this route, I'll probably remove some of those older debuggers pydb and pydbgr and put them in a separate repo.

An advantage of a separate repo is that you are in more control of things. 

Let me know how you want to proceed.

**Comment by seanfarley** [comment]
Ok, I added some tests. Since I haven't had much to work on this, I'd like to keep this as-is (but feel free to split it apart if you want). Hopefully, this will still make it to melpa soon enough :-)

**Comment by rocky** [comment]
Sure. I haven't had time either. Plan now is to remove some old python and ruby debuggers and put them in separate repositories. 

Then I'll add this. That minimizes the manual update that needs to be done in melpa.

Again, thanks for contributing.

**Comment by rocky** [comment]
So as to batch adding ipdb while removing a number of my older debuggers, I have not rebased your pull request off of the reduced-debuggers branch. Will be contacting melpa folks to see how they want to handle. 

So although this looks closed, it is really part of this bigger thing and will eventually get merged to master.

**Comment by seanfarley** [comment]
:+1:

**Comment by butala** [comment]
Hello,

I tried the build available via MELPA. Everything works as expected but interaction with ipdb hangs when I hit tab. I checked messages buffer and so forth as was did not find any logged errors.

Is there some additional information that I could provide that would help to debug this issue?

**Comment by rocky** [comment]
@butala well, there are the usual things one does in troubleshooting and bug reporting. Come up with the simplest sequence of events, working on the simplest python program that causes the problem. Then report that. The first step in in troubleshooting and fixing a bug is to have repeating sequence that a bug fixer can use to reproduce the problem.

**Comment by butala** [comment]
The problem manifests in the simplest example I can come up with:
1) I have a simple python code /tmp/test.py:
     if __name__ == '__main__':
        x_test = 1
        print('Hello world')
2) From a "fresh" run of emacs (only editing this code), I do `load-library realgud`
3) Then run ipdb with `ipdb`
4) I'm prompted for how to run ipdb, I enter `ipdb /tmp/test.py`
5) I see the ipdb interaction on the right and code with current statement marker on the right (good)
6) To verify interaction with ipdb works, I enter `h` and get the help message (good)
7) I hit `s` and enter to step, marker moves forward (good)
8) Hit `s` and enter again and now past `x = 1` (good)
9) I type `x` (hoping to tab complete `x_tab`) but never get to that point. Everything hangs as soon as I type `x`. 

I tried this from command line and no problems. I am on osx and use the homebrew build of python if that is of any consequence.

**Comment by seanfarley** [comment]
Can you try running the raw python?

```python
from IPython import get_ipython
comp = 'x'
';'.join(get_ipython().complete(comp.split()[-1] if len(comp) else '', comp)[1]
```

**Comment by butala** [comment]
When I run the above (though note missing right paren on last line) through the python interpreter I get this result:

    >>> from IPython import get_ipython
    >>> comp = 'x'
    >>> ';'.join(get_ipython().complete(comp.split()[-1] if len(comp) else '', comp)[1])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'NoneType' object has no attribute 'complete'

When I run in ipython, I get this result:

    In [1]: from IPython import get_ipython
    In [2]: comp = 'x'
    In [3]: ';'.join(get_ipython().complete(comp.split()[-1] if len(comp) else '', comp)[1])
    Out[3]: '%xdel;%xmode;xrange'

**Comment by seanfarley** [comment]
That's weird. Hmmm, I don't really know what's going on your system.

**Comment by rocky** [comment]
@seanfarley So let me summarize to see if I understand what's going on.

The ipython tests outside of realgud I guess, were to just test what's going on with completion.  Presumably  realgud hooks into that and that's where we think things are hanging, right? 

And there is unexplained behavior when run in a python shell and importing ipython versus starting ipython, right? 

So if the above is the case,  that behavior could explain why in realgud's ipdb things are hanging because it is more like running from a python shell and importing IPython. 

So the two avenues to for fixing would be to find out what's going on outside of realgud with IPython because there is possibly some additional setup. And the other avenue is some kind of error recovery thing in realgud so that if a command doesn't complete in a certain period of time, realgud errors out rather than hangs. 

Of course these two improvements are not mutually exclusive.

**Comment by seanfarley** [comment]
As the 'i' in `ipdb` suggests, `IPython` is a requirement of `ipdb`. I just tried to import from good, ol' regular python and it still works fine for me. I also tried importing `ipdb` and that, too, worked. So, I really don't know what's going on :-(

**Comment by butala** [comment]
I tried the above 3 lines of python on our linux server. It gives the same result (`AttributeError: 'NoneType' object has no attribute 'complete'`) as on my mac laptop.

Just another data point.

**Comment by seanfarley** [comment]
Ah, ok, I think I see now.

**Comment by seanfarley** [comment]
Ok, I'm an idiot.

**Comment by Wilfred** [comment]
Exciting! Can we add ipdb to https://github.com/rocky/emacs-dbgr/wiki/Debuggers-Supported now?

**Comment by rocky** [comment]
Sure. Anyone can edit the wiki.

**Comment by Wilfred** [comment]
I've added ipdb to that page :)

**Pull request closed without merging**
