### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amelio-vazquez-reina**
Expanded the installation instructions and added a link to the wiki with alternative installation instructions.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Awesome, thanks! Can you squash your commits into one? Then I'll happily merge :)

**Comment by amelio-vazquez-reina** [comment]
Thanks. I think @rocky just merged it, so we are good. Sorry I didn't squash earlier.

**Comment by cpitclaudel** [comment]
@rocky I think you wanted to merge this into master, not into `new-README`, right? :)
@amelio-vazquez-reina No problem at all.

**Comment by rocky** [comment]
Yes I meant master. I make lots of mistakes. That's one reason I work on debuggers.

**Comment by cpitclaudel** [comment]
No problem :) Can I take care of it, or do you want to?

**Comment by rocky** [comment]
You handle - thanks.

**Comment by cpitclaudel** [comment]
Sure thing :)

**Comment by cpitclaudel** [comment]
All done :) I squashed the commits and pushed them to master.
@amelio-vazquez-reina, thanks again! Hands-on contributions like this one are very welcome :)

**Pull request merged**
