### PR TITLE
Rewrite README

### LINKED ISSUE #72: Quickstart
Is there any documentation listing commands/shortcuts on common things like:
toggle breakpoints
print values
print frame
etc

Please let me know if I'm not seeing it in the docs or I'm supposed to dig it up elsewhere.

Thanks

### PR DESCRIPTION
**Pull request by cpitclaudel**
Screenshot is auto-generated using etc/screenshot.el. Closes #72.

Feel free to rephrase the "with contributions by" part :) Hopefully this helps newcomers!

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Preview here: https://github.com/rocky/emacs-dbgr/blob/new-README/README.md

**Comment by cpitclaudel** [comment]
Also inviting @amelio-vazquez-reina to the discussion, since he's contributed very nice IPDB docs

**Comment by rocky** [comment]
You deserve more credit than "with contributions". Should also add yourself to THANKS.

**Comment by cpitclaudel** [comment]
Haha :) I'll leave the addition to THANKS to you; I'd feel somewhat strange writing that commit. I'd be happy with "and" instead of "with contributions by" in the README, if you feel like pushing that :) but these are minor things: the pleasure is all mine to contribute to this cool project.

**Comment by amelio-vazquez-reina** [comment]
The new README.md looks *phenomenal*. Nice job @cpitclaudel! I added a new PR on top of yours here: https://github.com/rocky/emacs-dbgr/pull/107

**Pull request merged**
