### PR TITLE
Fix 83 and 88: refactor cmds.el

### PR DESCRIPTION
**Pull request by cpitclaudel**
This changes the surprising semantics described in #88. This is just a draft; it needs proofreading, since it's a larger change than usual.

Context: currently, `cmd-remap` not only runs a command: it also defines a key for that command in the `C-c` map. This is somewhat unpredictable (since one needs to run the command first for it to be defined), and it also goes again the Emacs guideline of not using `C-c letter` for package bindings.

Some clarifications:

* In perldb and nodejs I did minor cleanups, including removing a remapping where setting the hash properly seemed to have the same effect.
* I added to the shortkey keymap most of the keys that ended up in the C-c map after running each command once. For example running cmd-clear would previously also define `C-c X` as clear, so I added `X` for clear to the shortkey mode map.

Some questions and RFCs:

* Do other, external packages use `cmd-remap`? If so, I'll re-introduce it as a compatibility alias.
* There were some inconsistencies: for example running `step` and `step-no-arg` would both rebind `C-c s`. I kept the regular `s` that was already in `shortkey-mode-map`
* `C-c f`was being bound to `frame`, but `f` is already taken by finish. 
* Do other keymaps need to be updated?

### CODE REVIEW

**Comment by rocky** [comment]
Yes, I am afraid other packages right now use `cmd-remap`. Look for other repositories I own that start realgud.  Since this is good stuff of course I'll eventually take care of, but for now compatibility would be nice (if there happens to be yet other external code or forks of my external code).

As for which way to go when there were ambiguities either way is fine, so what you did is fine.  I don't think any other maps need updating.

Thanks for handling. I believe this screwy behavior is holdover from gud.el.

**Comment by cpitclaudel** [comment]
Got it; will update PR soon.

**Comment by cpitclaudel** [comment]
Ok, updated :) New PR has a compatibility alias.

**Comment by rocky** [comment]
Just made a scan of the external realgud debuggers. I should have done that before. 

None of them use realgud:cmd-remap, so sorry for the extra work. It is probably good practice though, and you never know who else is using that.

**Comment by cpitclaudel** [comment]
No problem at all. It's generally a bad idea to start breaking everything one day after getting commit rights, so I'm happy we added the compatibility wrapper :)

**Pull request merged**
